<?php

namespace Workflow\Http\Controllers;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Workflow\Models\WorkflowInstance;
use Workflow\Support\TransitionEngine;

/**
 * The inbound endpoint an external system POSTs to in order to fire a
 * `trigger: 'webhook'` edge on a specific workflow instance — see
 * packages/workflow/docs/webhooks.md for the full integrator-facing
 * contract (URL shape, signing, request/response bodies). In short:
 *
 * - The URL is generated by the app itself, via HasWorkflow::signedWebhookUrl(),
 *   and is a Laravel signed URL (`routes/workflow.php` applies the built-in
 *   'signed' middleware) — an integrator never constructs or signs this URL
 *   themselves, only stores/calls the one they were given.
 * - Runs as "system": no actor_rule check at all (there's no logged-in user
 *   to check one against), same convention TransitionEngine already uses for
 *   timer- and automatic-triggered edges. Preconditions and required
 *   `inputs` are still fully enforced — a webhook cannot force through data
 *   the graph itself would otherwise reject.
 * - Only ever fires the ONE edge named in the URL, and only if that edge's
 *   own `trigger` is `webhook` — a signed URL for one edge can never be
 *   (ab)used to fire a `manual`/role-gated edge instead.
 */
class WorkflowWebhookController
{
    public function __invoke(Request $request, WorkflowInstance $workflowInstance, string $edgeId, TransitionEngine $engine): JsonResponse
    {
        $version = $workflowInstance->effectiveVersion();
        $edge = $version?->edge($edgeId);

        if (! $edge) {
            return response()->json(['ok' => false, 'error' => "Edge [{$edgeId}] does not exist on this instance's graph."], 404);
        }

        if (($edge['trigger'] ?? null) !== 'webhook') {
            return response()->json(['ok' => false, 'error' => "Edge [{$edgeId}] is not a webhook-triggered edge."], 422);
        }

        $token = $workflowInstance->activeTokens()->where('node_id', $edge['from'])->first();

        if (! $token) {
            return response()->json(['ok' => false, 'error' => 'This edge is not available from the instance\'s current node.'], 422);
        }

        $inputs = (array) $request->input('inputs', []);

        $history = $engine->transition($token, $edgeId, $inputs, null, true);

        if (! $history) {
            return response()->json(['ok' => false, 'error' => 'The transition did not fire — a precondition was not met, or a required input was missing.'], 422);
        }

        return response()->json(['ok' => true, 'edge_id' => $edgeId, 'to' => $edge['to']]);
    }
}
